module.exports = {
    'Change group': 'Zmiana grupy',
    'Changing group': 'Zmiana grupy',
    'Loading groups': 'Ladowanie grup',
    'put-into-new-group': 'Do nowej grupy',

    'Select Group Order Rule': 'Wybierz regułę',
    'group-order-rule-label-BB': 'Bilans Piłek',
    'group-order-rule-label-WM': 'Wygranę Meczi',
    'group-order-rule-label-f2f': 'Twarzą w Twarz',
    'group-order-rule-label-LB': 'Straconę Piłki',
    'group-order-rule-label-LS': 'Straconę Sety',
    'group-order-rule-label-rnd': 'Losowanie',
    'group-order-rule-label-SB': 'Bilans Setów',
    'group-order-rule-label-WB': 'Wygranę Piłki',
    'group-order-rule-label-WS': 'Wygranę Sety',
    'group-order-rule-label-Punkts': 'Suma Punktów',
    'group-order-rule-label-DM': 'Dodatkowe meczi',

    'group-rule-parameters-title': 'Ustawenia dla: ',
    'group-order-rule-list-lbl': 'Lista regul uporządkowania',

    'match-outcome-scope-lbl': 'Liczyć przerwanę meczi',
    'match-outcome-scope-lbl-ALL_MATCHES': 'Tak',
    'match-outcome-scope-lbl-JUST_NORMALLY_COMPLETE': 'Nie',
    'match-participant-scope-lbl': 'Liczyć meczi tylko mędzę spórnymi graczami',
    'match-participant-scope-lbl-BOTH': 'Tak',
    'match-participant-scope-lbl-AT_LEAST_ONE': 'Nie',

    'custom-dm-match-rules-lbl': 'Niezależyne reguly dodatkowych meczów',

    'rule-column-header-Tennis-BallsBalance': '⚫-⚪',
    'rule-column-header-Tennis-WonMatches': '∑🏆',
    'rule-column-header-Tennis-F2F': '☺☻',
    'rule-column-header-Tennis-LostBalls': '⚪',
    'rule-column-header-Tennis-LostSets': '♺🎾',
    'rule-column-header-Tennis-Random': '⚄⚂',
    'rule-column-header-Tennis-SetsBalance': 'Δ🎾',
    'rule-column-header-Tennis-WonBalls': '⚫',
    'rule-column-header-Tennis-WonSets': '🎾',
    'rule-column-header-Tennis-Punkts': '∑',

    'rule-column-header-PingPong-BallsBalance': '⚫-⚪',
    'rule-column-header-PingPong-WonMatches': '∑🏆',
    'rule-column-header-PingPong-F2F': '☺☻',
    'rule-column-header-PingPong-LostBalls': '⚪',
    'rule-column-header-PingPong-LostSets': '♺🏓',
    'rule-column-header-PingPong-Random': '⚄⚂',
    'rule-column-header-PingPong-SetsBalance': 'Δ🏓',
    'rule-column-header-PingPong-WonBalls': '⚫',
    'rule-column-header-PingPong-WonSets': '🏓',
    'rule-column-header-PingPong-Punkts': '∑'
};
