sudo: false
language: java
before_script:
  - echo "USE mysql;\nUPDATE user SET password=PASSWORD('password') WHERE user='root';\nFLUSH PRIVILEGES;\n" | mysql -u root
services:
  - mysql
script:
  - cp .travis.settings.xml $HOME/.m2/settings.xml
  - mvn -P upgrade-db install
