sudo: false
language: java
services:
  - mysql
install:
  - echo "my install"
before_script:
  - echo "USE mysql;\nUPDATE user SET password=PASSWORD('password') WHERE user='root';\nFLUSH PRIVILEGES;\n" | mysql -u root
script:
  - echo "my script"
  - cp .travis.settings.xml $HOME/.m2/settings.xml
  - mvn -P upgrade-db -pl setup-env/docker-containers install
  - mvn -pl ping-pong -am install
deploy:
  provider: script
  script: echo "my deploy"
