'use strict';

angular.module('pingPong', [
    'ngRoute',
    'mainMenu',
    'core',
    'signUp',
    'signIn',
    'doSignIn',
    'account',
    'placeList',
    'placeDetail',
    'newPlace',
    'placePicker',
    'myTournamentList',
    'playInTournamentList',
    'newTournament',
    'newTournamentParameters',
    'myTournament',
    'matchStateDescription',
    'completeMyMatch',
    'completeMatch',
    'participantPresence',
    'tournamentCategories',
    'tournamentDetail',
    'myMatchPlayList',
    'myMatchJudgeList',
    'openTournamentList',
    'openTournament',
    'tournamentList'
]);
