module.exports = {
    'Change group': 'Change group',
    'Changing group': 'Changing group',
    'Loading groups': 'Loading groups',
    'put-into-new-group': 'Into a new group',
    'Select Group Order Rule': 'Select Group Order Rule',
    'group-order-rule-label-BB': 'Balls Balance',
    'group-order-rule-label-WM': 'Won Matches',
    'group-order-rule-label-f2f': 'Face-to-Face',
    'group-order-rule-label-LB': 'Lost Balls',
    'group-order-rule-label-LS': 'Lost Sets',
    'group-order-rule-label-rnd': 'Draw',
    'group-order-rule-label-SB': 'Sets Balance',
    'group-order-rule-label-WB': 'Won Balls',
    'group-order-rule-label-WS': 'Won Sets',
    'group-order-rule-label-Punkts': 'Score Sum',
    'group-order-rule-label-DM': 'Play extra matches',

    'group-rule-parameters-title': 'Parameters for ',
    'group-order-rule-list-lbl': 'List of order rules',

    'match-outcome-scope-lbl': 'Count broken matches',
    'match-outcome-scope-lbl-ALL_MATCHES': 'Yes',
    'match-outcome-scope-lbl-JUST_NORMALLY_COMPLETE': 'No',
    'match-participant-scope-lbl': 'Count only matches among competing players',
    'match-participant-scope-lbl-BOTH': 'Yes',
    'match-participant-scope-lbl-AT_LEAST_ONE': 'No',

    'custom-dm-match-rules-lbl': 'Custom rules for extra matches',

    'rule-column-header-Tennis-BB': '⚫-⚪',
    'rule-column-header-Tennis-WM': '∑🏆',
    'rule-column-header-Tennis-f2f': '☺☻',
    'rule-column-header-Tennis-LB': '⚪',
    'rule-column-header-Tennis-LS': '♺🎾',
    'rule-column-header-Tennis-rnd': '⚄⚂',
    'rule-column-header-Tennis-SB': 'Δ🎾',
    'rule-column-header-Tennis-WB': '⚫',
    'rule-column-header-Tennis-WS': '🎾',
    'rule-column-header-Tennis-Punkts': '∑',
    'rule-column-header-Tennis-DM': 'DM', // not used


    'rule-column-header-PingPong-BB': '⚫-⚪',
    'rule-column-header-PingPong-WM': '∑🏆',
    'rule-column-header-PingPong-f2f': '☺☻',
    'rule-column-header-PingPong-LB': '⚪',
    'rule-column-header-PingPong-LS': '♺🏓',
    'rule-column-header-PingPong-rnd': '⚄⚂',
    'rule-column-header-PingPong-SB': 'Δ🏓',
    'rule-column-header-PingPong-WB': '⚫',
    'rule-column-header-PingPong-WS': '🏓',
    'rule-column-header-PingPong-Punkts': '∑',
    'rule-column-header-PingPong-DM': 'DM' // not used
};
