module.exports = {
    'Change group': 'Change group',
    'Changing group': 'Changing group',
    'Loading groups': 'Loading groups',
    'put-into-new-group': 'Into a new group',
    'Select Group Order Rule': 'Select Group Order Rule',
    'group-order-rule-label-BB': 'Balls Balance',
    'group-order-rule-label-WM': 'Won Matches',
    'group-order-rule-label-f2f': 'Face-to-Face',
    'group-order-rule-label-LB': 'Lost Balls',
    'group-order-rule-label-LS': 'Lost Sets',
    'group-order-rule-label-rnd': 'Draw',
    'group-order-rule-label-SB': 'Sets Balance',
    'group-order-rule-label-WB': 'Won Balls',
    'group-order-rule-label-WS': 'Won Sets',
    'group-order-rule-label-WtMbS': 'Weighted matches',
    'group-order-rule-label-AtpWMS': 'ATP weighted matches',
    'group-order-rule-label-AtpDI': 'ATP part d.i',
    'group-order-rule-label-AtpDII': 'ATP part d.ii',
    'group-order-rule-label-AtpDIII': 'ATP part d.iii',
    'group-order-rule-label-Punkts': 'Score Sum',
    'group-order-rule-label-DM': 'Play extra matches',

    'group-rule-parameters-title': 'Parameters for ',
    'group-order-rule-list-lbl': 'List of order rules',

    'match-outcome-scope-lbl': 'Count broken matches',
    'match-outcome-scope-lbl-ALL_MATCHES': 'Yes',
    'match-outcome-scope-lbl-JUST_NORMALLY_COMPLETE': 'No',
    'match-participant-scope-lbl': 'Count only matches among competing players',
    'match-participant-scope-lbl-BOTH': 'Yes',
    'match-participant-scope-lbl-AT_LEAST_ONE': 'No',

    'custom-dm-match-rules-lbl': 'Custom rules for extra matches',

    'rule-column-header-Tennis-BallsBalance': '⚫-⚪',
    'rule-column-header-Tennis-WonMatches': '∑🏆',
    'rule-column-header-Tennis-F2F': '☺☻',
    'rule-column-header-Tennis-LostBalls': '⚪',
    'rule-column-header-Tennis-LostSets': '♺🎾',
    'rule-column-header-Tennis-Random': '⚄⚂',
    'rule-column-header-Tennis-SetsBalance': 'Δ🎾',
    'rule-column-header-Tennis-WonBalls': '⚫',
    'rule-column-header-Tennis-WonSets': '🎾',
    'rule-column-header-Tennis-Punkts': '∑',

    'rule-column-header-PingPong-BallsBalance': '⚫-⚪',
    'rule-column-header-PingPong-WonMatches': '∑🏆',
    'rule-column-header-PingPong-F2F': '☺☻',
    'rule-column-header-PingPong-LostBalls': '⚪',
    'rule-column-header-PingPong-LostSets': '♺🏓',
    'rule-column-header-PingPong-Random': '⚄⚂',
    'rule-column-header-PingPong-SetsBalance': 'Δ🏓',
    'rule-column-header-PingPong-WonBalls': '⚫',
    'rule-column-header-PingPong-WonSets': '🏓',
    'rule-column-header-PingPong-Punkts': '∑'
};
