module.exports = {
        // new place
    'city name': 'City',
    'place-name-length': 'Name length must be less than {{max}} letters',
    'country name': 'Country',
    'Add new country': 'Add new country',
    'Country is required': 'Country is required',
    'Add new city': 'Add new city',
    'City is required': 'City is required',
    'Address is required': 'Address is required',
    'postal-address-length': 'Name length must be less than {{max}} letters',
    'Create Place': 'Create Place',
    'Optional field': 'Optional field',
    'New country': 'New country',
    'Name': 'Name',
    'Country name is required': 'Country name is required',
    'country-name-length': 'Country name length must be less than {{max}} letters',
    'Add & Use': 'Add & Use',
    'New city': 'New city',
    'City name is required': 'City name is required',
    'city-name-length': 'City name length must be less than {{max}} letters',
    'New Place': 'New Place',
    'Creating city': 'Creating city',
    'Creating country': 'Creating country',
    'Creating place': 'Creating place',
    'Cities': 'Cities',
    'Countries': 'Countries'
};
